/**
 * Assignment and Function Config Panels
 * Extracted from NodeConfigPanel.js
 */
import React from 'react';
import { Label } from '../../../../components/ui/label';
import { Input } from '../../../../components/ui/input';
import { Textarea } from '../../../../components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../../../components/ui/select';
import { Button } from '../../../../components/ui/button';
import { Trash2, Plus } from 'lucide-react';
import ResourcePickerField from '../ResourcePickerField';

// Utility: Generate API name
const generateApiName = (label) => {
  if (!label) return '';
  return label.toLowerCase().trim().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
};

/**
 * Assignment Config Panel
 */
export const AssignmentConfigPanel = ({ 
  config, 
  setConfig, 
  flowVariables, 
  onCreateVariable,
  isInsideLoop,
  loopObjectName,
  nodes = []
}) => {
  const updateAssignment = (index, updates) => {
    const newAssignments = [...(config.assignments || [])];
    newAssignments[index] = { ...newAssignments[index], ...updates };
    setConfig({ ...config, assignments: newAssignments });
  };

  const addAssignment = () => {
    const newAssignments = [...(config.assignments || []), { variable: '', operator: 'assign', value: '' }];
    setConfig({ ...config, assignments: newAssignments });
  };

  const removeAssignment = (index) => {
    const newAssignments = (config.assignments || []).filter((_, i) => i !== index);
    setConfig({ ...config, assignments: newAssignments });
  };

  return (
    <div className="space-y-4">
      {/* Loop Context Notice */}
      {isInsideLoop && loopObjectName && (
        <div className="bg-amber-50 border border-amber-300 rounded-lg p-3">
          <p className="text-sm text-amber-900 font-semibold flex items-center gap-2">
            <span>🔁</span> Inside Loop Context
          </p>
          <p className="text-xs text-amber-700 mt-1">
            You can reference current item fields using <code className="bg-amber-100 px-1 rounded">{'{{' + loopObjectName + '_fieldname}}'}</code>
          </p>
        </div>
      )}

      <div className="bg-green-50 border border-green-200 rounded-lg p-3">
        <p className="text-sm text-green-800 font-medium">📝 Assignment Element</p>
        <p className="text-xs text-green-600 mt-1">
          Set or change the value of a variable or field
        </p>
      </div>

      {/* Label and API Name */}
      <div className="grid grid-cols-2 gap-3">
        <div>
          <Label>Label</Label>
          <Input
            className="w-full"
            value={config.label || ''}
            onChange={(e) => {
              const newLabel = e.target.value;
              const currentApiName = config.api_name || '';
              const oldAutoGeneratedApiName = generateApiName(config.label || '');
              const shouldAutoGenerate = !currentApiName || currentApiName === oldAutoGeneratedApiName;
              setConfig({ 
                ...config, 
                label: newLabel,
                api_name: shouldAutoGenerate ? generateApiName(newLabel) : currentApiName
              });
            }}
            placeholder="e.g., Set Account Status"
          />
        </div>
        <div>
          <Label>API Name</Label>
          <Input
            className="w-full font-mono bg-slate-50"
            value={config.api_name || ''}
            onChange={(e) => setConfig({ ...config, api_name: e.target.value })}
            placeholder="set_account_status"
          />
        </div>
      </div>

      {/* Description */}
      <div>
        <Label>Description <span className="text-slate-400 font-normal">(Optional)</span></Label>
        <Textarea
          className="w-full mt-1"
          value={config.description || ''}
          onChange={(e) => setConfig({ ...config, description: e.target.value })}
          placeholder="Describe what this assignment does..."
          rows={2}
        />
      </div>

      {/* Formula Examples */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
        <p className="text-sm text-blue-800 font-medium mb-2">📐 Formula Examples</p>
        <div className="grid grid-cols-2 gap-2 text-xs">
          <div>
            <span className="font-semibold text-slate-700">String:</span>
            <code className="ml-1 bg-blue-100 px-1 rounded text-blue-900">&quot;AutoOpp&quot; + Trigger.Lead.FirstName</code>
          </div>
          <div>
            <span className="font-semibold text-slate-700">Date:</span>
            <code className="ml-1 bg-blue-100 px-1 rounded text-blue-900">TODAY() + 7</code>
          </div>
          <div>
            <span className="font-semibold text-slate-700">Number:</span>
            <code className="ml-1 bg-blue-100 px-1 rounded text-blue-900">LEN(Trigger.Lead.LastName) * 100</code>
          </div>
          <div>
            <span className="font-semibold text-slate-700">Functions:</span>
            <code className="ml-1 bg-blue-100 px-1 rounded text-blue-900">TODAY(), NOW(), LEN(), FIND()</code>
          </div>
        </div>
      </div>

      {/* Variable Assignments */}
      <div>
        <Label className="text-sm font-semibold">Variable Assignments</Label>
        <div className="space-y-3 mt-2">
          {(config.assignments || []).map((assignment, index) => (
            <div key={index} className="p-3 bg-slate-50 rounded-lg border border-slate-200">
              <div className="flex items-center gap-2">
                <span className="text-xs font-mono text-slate-400 w-6">{index + 1}.</span>
                
                {/* Variable - ResourcePickerField */}
                <div className="flex-1">
                  <Label className="text-xs text-slate-500 mb-1 block">Variable</Label>
                  <ResourcePickerField
                    value={assignment.variable || ''}
                    onChange={(value) => updateAssignment(index, { variable: value })}
                    flowVariables={flowVariables}
                    onCreateVariable={onCreateVariable}
                    nodes={nodes}
                    placeholder="Select or type variable name..."
                  />
                </div>
                
                {/* Operator */}
                <div className="w-32">
                  <Label className="text-xs text-slate-500 mb-1 block">Operator</Label>
                  <Select
                    value={assignment.operator || 'assign'}
                    onValueChange={(value) => updateAssignment(index, { operator: value })}
                  >
                    <SelectTrigger className="w-full">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="assign">Equals (=)</SelectItem>
                      <SelectItem value="add">Add (+)</SelectItem>
                      <SelectItem value="subtract">Subtract (-)</SelectItem>
                      <SelectItem value="add_item">Add Item</SelectItem>
                      <SelectItem value="add_at_start">Add at Start</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                
                {/* Value - ResourcePickerField */}
                <div className="flex-1">
                  <Label className="text-xs text-slate-500 mb-1 block">Value</Label>
                  <ResourcePickerField
                    value={assignment.value || ''}
                    onChange={(value) => updateAssignment(index, { value: value })}
                    flowVariables={flowVariables}
                    onCreateVariable={onCreateVariable}
                    nodes={nodes}
                    placeholder="Type formula or select value..."
                  />
                </div>
                
                {(config.assignments || []).length > 1 && (
                  <button
                    type="button"
                    onClick={() => removeAssignment(index)}
                    className="p-2 text-red-600 hover:bg-red-50 rounded-md mt-5"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                )}
              </div>
            </div>
          ))}
          
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={addAssignment}
            className="w-full border-dashed border-2"
          >
            <Plus className="w-4 h-4 mr-2" /> Add Assignment
          </Button>
        </div>
      </div>
    </div>
  );
};

/**
 * Function Config Panel (Custom Apex-like)
 */
export const FunctionConfigPanel = ({ config, setConfig, handleConfigChange, flowVariables }) => {
  return (
    <div className="space-y-4">
      <div className="bg-purple-50 border border-purple-200 rounded-lg p-3">
        <p className="text-sm text-purple-800 font-medium">🔧 Custom Function</p>
        <p className="text-xs text-purple-600 mt-1">
          Execute custom logic or transformations
        </p>
      </div>

      <div>
        <Label>Function Name</Label>
        <Input
          className="w-full"
          value={config.function_name || ''}
          onChange={(e) => handleConfigChange('function_name', e.target.value)}
          placeholder="e.g., calculateDiscount"
        />
      </div>

      <div>
        <Label>Function Code</Label>
        <Textarea
          className="w-full font-mono text-sm"
          value={config.code || ''}
          onChange={(e) => handleConfigChange('code', e.target.value)}
          placeholder="// Enter your function logic here&#10;return value * 0.1;"
          rows={8}
        />
        <p className="text-xs text-slate-500 mt-1">
          Use JavaScript syntax. Access variables with $Flow.variableName
        </p>
      </div>

      <div>
        <Label>Return Variable</Label>
        <Input
          className="w-full"
          value={config.return_variable || ''}
          onChange={(e) => handleConfigChange('return_variable', e.target.value)}
          placeholder="result"
        />
      </div>
    </div>
  );
};

export default { AssignmentConfigPanel, FunctionConfigPanel };
