/**
 * MCP (CRM Action) Config Panel
 * Extracted from NodeConfigPanel.js - handles create, update, get, delete operations
 */
import React from 'react';
import { Label } from '../../../../components/ui/label';
import { Input } from '../../../../components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../../../components/ui/select';
import { Button } from '../../../../components/ui/button';
import { Trash2 } from 'lucide-react';
import ComboField from '../ComboField';
import ResourcePickerField from '../ResourcePickerField';

// Utility: Generate API name from label
const generateApiName = (label) => {
  if (!label) return '';
  return label.toLowerCase().trim().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
};

const MCPConfigPanel = ({
  config,
  setConfig,
  handleConfigChange,
  availableFields,
  flowVariables,
  isInsideLoop,
  loopObjectName,
  objectsList,
  onCreateVariable,
  fetchFieldsForObject,
  triggerObject
}) => {
  // Get combined fields from various sources
  const getCombinedFieldsForMerging = () => {
    const combined = [];
    
    // Add trigger fields
    if (triggerObject && availableFields.length > 0) {
      availableFields.forEach(field => {
        combined.push({
          value: `{{Trigger.${triggerObject}.${field.api_name || field.name}}}`,
          label: `Trigger: ${field.label || field.name}`,
          group: 'Trigger Fields'
        });
      });
    }
    
    // Add flow variables
    flowVariables.forEach(v => {
      combined.push({
        value: `{{${v.name}}}`,
        label: v.name,
        type: v.dataType,
        group: 'Variables'
      });
    });
    
    // Add loop context if inside loop
    if (isInsideLoop && loopObjectName) {
      combined.push({
        value: `{{${loopObjectName}_Id}}`,
        label: `${loopObjectName} ID (current item)`,
        group: 'Loop Context'
      });
    }
    
    return combined;
  };

  const combinedFields = getCombinedFieldsForMerging();

  return (
    <div className="space-y-4">
      {/* Loop Context Notice */}
      {isInsideLoop && loopObjectName && (
        <div className="bg-amber-50 border border-amber-300 rounded-lg p-3 mb-2">
          <p className="text-sm text-amber-900 font-semibold flex items-center gap-2">
            <span>🔁</span> Inside Loop Context
          </p>
          <p className="text-xs text-amber-700 mt-1">
            This action runs for each <strong>{loopObjectName}</strong> in the collection.
            You can reference current item fields using <code className="bg-amber-100 px-1 rounded">{'{{' + loopObjectName + '_fieldname}}'}</code>
          </p>
        </div>
      )}

      <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4">
        <p className="text-sm text-blue-800 font-medium">🔄 CRM Action Node</p>
        <p className="text-xs text-blue-600 mt-1">
          Perform create, update, get, or delete operations on CRM records.
        </p>
      </div>

      {/* Action Type */}
      <div>
        <Label>Action Type</Label>
        <Select
          value={config.action_type || 'create'}
          onValueChange={(value) => {
            setConfig({ 
              ...config, 
              action_type: value,
              field_values: value === 'create' || value === 'update' ? [{ field: '', value: '' }] : undefined,
              record_id: value === 'create' ? undefined : config.record_id,
              filter_conditions: value === 'get' ? [{ field: '', operator: 'equals', value: '' }] : undefined
            });
          }}
        >
          <SelectTrigger className="w-full">
            <SelectValue placeholder="Select action type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="create">Create Record</SelectItem>
            <SelectItem value="update">Update Record</SelectItem>
            <SelectItem value="get">Get Record</SelectItem>
            <SelectItem value="delete">Delete Record</SelectItem>
          </SelectContent>
        </Select>
        <p className="text-xs text-slate-500 mt-1">
          {config.action_type === 'create' && '➕ Create a new record'}
          {config.action_type === 'update' && '✏️ Update an existing record'}
          {config.action_type === 'get' && '🔍 Retrieve record(s) by filters'}
          {config.action_type === 'delete' && '🗑️ Delete an existing record'}
        </p>
      </div>

      {/* Label and API Name */}
      <div className="grid grid-cols-2 gap-3">
        <div>
          <Label>Label</Label>
          <Input
            className="w-full"
            value={config.label || ''}
            onChange={(e) => {
              const newLabel = e.target.value;
              const currentApiName = config.api_name || '';
              const oldAutoGeneratedApiName = generateApiName(config.label || '');
              const shouldAutoGenerate = !currentApiName || currentApiName === oldAutoGeneratedApiName;
              setConfig({ 
                ...config, 
                label: newLabel,
                api_name: shouldAutoGenerate ? generateApiName(newLabel) : currentApiName
              });
            }}
            placeholder="e.g., Create Lead"
          />
        </div>
        <div>
          <Label>API Name</Label>
          <Input
            className="w-full font-mono bg-slate-50"
            value={config.api_name || ''}
            onChange={(e) => setConfig({ ...config, api_name: e.target.value })}
            placeholder="api_name"
          />
        </div>
      </div>

      {/* Object Type */}
      <div>
        <Label>Object Type</Label>
        <Select
          value={config.object || ''}
          onValueChange={async (value) => {
            handleConfigChange('object', value);
            if (fetchFieldsForObject) {
              await fetchFieldsForObject(value);
            }
          }}
        >
          <SelectTrigger className="w-full">
            <SelectValue placeholder="Select object" />
          </SelectTrigger>
          <SelectContent>
            {(objectsList || []).map(obj => (
              <SelectItem key={obj.name} value={obj.name}>{obj.label}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Record ID for Update/Get/Delete */}
      {(config.action_type === 'update' || config.action_type === 'delete') && (
        <div>
          <Label>Record ID</Label>
          <ComboField
            value={config.record_id || ''}
            onChange={(value) => handleConfigChange('record_id', value)}
            options={combinedFields}
            placeholder="Select or enter record ID"
          />
          <p className="text-xs text-slate-500 mt-1">
            The ID of the record to {config.action_type}
          </p>
        </div>
      )}

      {/* Field Values for Create/Update */}
      {(config.action_type === 'create' || config.action_type === 'update') && (
        <div>
          <Label>Field Values</Label>
          <p className="text-xs text-slate-500 mb-2">
            Set values for fields in the record
          </p>
          
          <div className="space-y-2">
            {(config.field_values || []).map((fieldValue, index) => (
              <div key={index} className="flex items-center gap-2 p-2 bg-slate-50 rounded-md">
                <Select
                  value={fieldValue.field || ''}
                  onValueChange={(value) => {
                    const newFieldValues = [...(config.field_values || [])];
                    newFieldValues[index] = { ...newFieldValues[index], field: value };
                    setConfig({ ...config, field_values: newFieldValues });
                  }}
                >
                  <SelectTrigger className="flex-1">
                    <SelectValue placeholder="Select field" />
                  </SelectTrigger>
                  <SelectContent>
                    {availableFields.map(field => (
                      <SelectItem key={field.api_name || field.name} value={field.api_name || field.name}>
                        {field.label || field.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <ComboField
                  value={fieldValue.value || ''}
                  onChange={(value) => {
                    const newFieldValues = [...(config.field_values || [])];
                    newFieldValues[index] = { ...newFieldValues[index], value: value };
                    setConfig({ ...config, field_values: newFieldValues });
                  }}
                  options={combinedFields}
                  placeholder="Value"
                  className="flex-1"
                />
                <button
                  type="button"
                  onClick={() => {
                    const newFieldValues = (config.field_values || []).filter((_, i) => i !== index);
                    setConfig({ ...config, field_values: newFieldValues });
                  }}
                  className="p-2 text-red-600 hover:bg-red-50 rounded-md"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            ))}
            
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => {
                const newFieldValues = [...(config.field_values || []), { field: '', value: '' }];
                setConfig({ ...config, field_values: newFieldValues });
              }}
              className="w-full border-dashed border-2"
            >
              + Add Field Value
            </Button>
          </div>
        </div>
      )}

      {/* Filter Conditions for Get */}
      {config.action_type === 'get' && (
        <div>
          <Label>Filter Conditions</Label>
          <p className="text-xs text-slate-500 mb-2">
            Specify criteria to find records
          </p>
          
          <div className="space-y-2">
            {(config.filter_conditions || []).map((condition, index) => {
              // Check if selected field is a date type
              const selectedField = availableFields.find(f => 
                (f.api_name || f.name) === condition.field ||
                condition.field?.includes('.')
              );
              const isDateField = selectedField?.dataType === 'datetime' || 
                                  selectedField?.dataType === 'date' ||
                                  condition.field?.toLowerCase()?.includes('date') ||
                                  condition.field?.toLowerCase()?.includes('created') ||
                                  condition.field?.toLowerCase()?.includes('modified');
              const isLastXDaysOperator = condition.operator === 'last_x_days' || condition.operator === 'next_x_days';
              
              // Build reference fields from availableFields
              const referenceFields = availableFields.filter(f => {
                const fieldName = (f.api_name || f.name || '').toLowerCase();
                return fieldName.endsWith('id') && fieldName !== 'id';
              });
              
              // Standard reference fields that should always be available
              const standardReferenceFields = [
                { api_name: 'AccountId', label: 'Account ID', refObject: 'Account' },
                { api_name: 'OwnerId', label: 'Owner ID', refObject: 'Owner' },
                { api_name: 'CreatedById', label: 'Created By ID', refObject: 'CreatedBy' },
                { api_name: 'LastModifiedById', label: 'Last Modified By ID', refObject: 'LastModifiedBy' },
                { api_name: 'ContactId', label: 'Contact ID', refObject: 'Contact' },
                { api_name: 'OpportunityId', label: 'Opportunity ID', refObject: 'Opportunity' },
                { api_name: 'CampaignId', label: 'Campaign ID', refObject: 'Campaign' },
              ];
              
              // Merge actual fields with standard ones (avoid duplicates)
              const existingRefNames = referenceFields.map(f => (f.api_name || f.name).toLowerCase());
              const allReferenceFields = [
                ...referenceFields,
                ...standardReferenceFields.filter(sf => !existingRefNames.includes(sf.api_name.toLowerCase()))
              ];
              
              // Regular fields (non-reference)
              const regularFields = availableFields.filter(f => {
                const fieldName = (f.api_name || f.name || '').toLowerCase();
                return !fieldName.endsWith('id');
              });
              
              // Standard regular fields
              const standardRegularFields = [
                { api_name: 'Name', label: 'Name', dataType: 'string' },
                { api_name: 'Email', label: 'Email', dataType: 'string' },
                { api_name: 'Phone', label: 'Phone', dataType: 'string' },
                { api_name: 'Status', label: 'Status', dataType: 'string' },
                { api_name: 'Type', label: 'Type', dataType: 'string' },
                { api_name: 'Stage', label: 'Stage', dataType: 'string' },
                { api_name: 'Amount', label: 'Amount', dataType: 'number' },
                { api_name: 'CreatedDate', label: 'Created Date', dataType: 'datetime' },
                { api_name: 'LastModifiedDate', label: 'Last Modified Date', dataType: 'datetime' },
                { api_name: 'CloseDate', label: 'Close Date', dataType: 'date' },
              ];
              
              const existingRegNames = regularFields.map(f => (f.api_name || f.name).toLowerCase());
              const allRegularFields = [
                ...regularFields,
                ...standardRegularFields.filter(sf => !existingRegNames.includes(sf.api_name.toLowerCase()))
              ];
              
              return (
                <div key={index} className="flex items-center gap-2 p-2 bg-slate-50 rounded-md flex-wrap">
                  {/* Field Selector with Reference Traversal */}
                  <Select
                    value={condition.field || ''}
                    onValueChange={(value) => {
                      const newConditions = [...(config.filter_conditions || [])];
                      newConditions[index] = { ...newConditions[index], field: value };
                      setConfig({ ...config, filter_conditions: newConditions });
                    }}
                  >
                    <SelectTrigger className="flex-1 min-w-[160px]">
                      <SelectValue placeholder="Select field" />
                    </SelectTrigger>
                    <SelectContent className="max-h-[350px]">
                      {/* Record ID ALWAYS FIRST */}
                      <SelectItem value="id" className="font-medium bg-purple-50">
                        <span className="flex items-center gap-2">
                          <span className="text-purple-600">🔑</span>
                          <span className="text-purple-700 font-semibold">Record ID</span>
                        </span>
                      </SelectItem>
                      
                      {/* Divider */}
                      <div className="px-2 py-1 text-[10px] text-slate-400 border-t mt-1 uppercase tracking-wide">
                        Reference Fields (Expandable)
                      </div>
                      
                      {/* Reference Fields with traversal */}
                      {allReferenceFields.map(field => {
                        const fieldName = field.api_name || field.name;
                        const refObjectName = field.refObject || fieldName.replace(/Id$/i, '').replace(/_id$/i, '');
                        const refObjCapitalized = refObjectName.charAt(0).toUpperCase() + refObjectName.slice(1);
                        return (
                          <React.Fragment key={fieldName}>
                            <SelectItem value={fieldName} className="font-medium text-blue-700 bg-blue-50/50">
                              <span className="flex items-center gap-2">
                                <span>🔗</span>
                                {field.label || fieldName} ▶
                              </span>
                            </SelectItem>
                            {/* Sub-fields for reference traversal */}
                            <SelectItem value={`${refObjCapitalized}.Id`} className="pl-8 text-sm text-slate-600">
                              └ {refObjCapitalized}.Id
                            </SelectItem>
                            <SelectItem value={`${refObjCapitalized}.Name`} className="pl-8 text-sm text-slate-600">
                              └ {refObjCapitalized}.Name
                            </SelectItem>
                            <SelectItem value={`${refObjCapitalized}.Email`} className="pl-8 text-sm text-slate-600">
                              └ {refObjCapitalized}.Email
                            </SelectItem>
                          </React.Fragment>
                        );
                      })}
                      
                      {/* Divider */}
                      <div className="px-2 py-1 text-[10px] text-slate-400 border-t mt-1 uppercase tracking-wide">
                        Standard Fields
                      </div>
                      
                      {/* Regular Fields */}
                      {allRegularFields.map(field => (
                        <SelectItem key={field.api_name || field.name} value={field.api_name || field.name}>
                          <span className="flex items-center gap-2">
                            {field.label || field.name}
                            {(field.dataType === 'datetime' || field.dataType === 'date') && (
                              <span className="text-xs text-slate-400">📅</span>
                            )}
                          </span>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  
                  {/* Operator Selector - Enhanced with Date operators */}
                  <Select
                    value={condition.operator || 'equals'}
                    onValueChange={(value) => {
                      const newConditions = [...(config.filter_conditions || [])];
                      newConditions[index] = { ...newConditions[index], operator: value };
                      // Reset value if switching to/from last_x_days
                      if (value === 'last_x_days' || value === 'next_x_days') {
                        newConditions[index].value = '7'; // Default 7 days
                      }
                      setConfig({ ...config, filter_conditions: newConditions });
                    }}
                  >
                    <SelectTrigger className="w-36">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="equals">= Equals</SelectItem>
                      <SelectItem value="not_equals">≠ Not Equals</SelectItem>
                      <SelectItem value="contains">Contains</SelectItem>
                      <SelectItem value="starts_with">Starts With</SelectItem>
                      <SelectItem value="greater_than">&gt; Greater Than</SelectItem>
                      <SelectItem value="less_than">&lt; Less Than</SelectItem>
                      <SelectItem value="greater_than_or_equal">≥ Greater Or Equal</SelectItem>
                      <SelectItem value="less_than_or_equal">≤ Less Or Equal</SelectItem>
                      {/* Date-specific operators - ALWAYS SHOWN for easy access */}
                      <div className="px-2 py-1 text-[10px] text-slate-400 border-t mt-1">Date Filters</div>
                      <SelectItem value="last_x_days" className="text-blue-700 font-medium">
                        📅 Last X Days
                      </SelectItem>
                      <SelectItem value="next_x_days" className="text-green-700 font-medium">
                        📅 Next X Days
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  
                  {/* Value Input - Numeric for Last X Days, ComboField otherwise */}
                  {isLastXDaysOperator ? (
                    <div className="flex items-center gap-1 flex-1 min-w-[100px]">
                      <Input
                        type="number"
                        min="1"
                        max="365"
                        value={condition.value || '7'}
                        onChange={(e) => {
                          const newConditions = [...(config.filter_conditions || [])];
                          newConditions[index] = { ...newConditions[index], value: e.target.value };
                          setConfig({ ...config, filter_conditions: newConditions });
                        }}
                        className="w-20"
                        placeholder="Days"
                      />
                      <span className="text-xs text-slate-500">days</span>
                    </div>
                  ) : (
                    <ComboField
                      value={condition.value || ''}
                      onChange={(value) => {
                        const newConditions = [...(config.filter_conditions || [])];
                        newConditions[index] = { ...newConditions[index], value: value };
                        setConfig({ ...config, filter_conditions: newConditions });
                      }}
                      options={combinedFields}
                      placeholder="Value"
                      className="flex-1 min-w-[120px]"
                    />
                  )}
                  
                  {(config.filter_conditions || []).length > 1 && (
                    <button
                      type="button"
                      onClick={() => {
                        const newConditions = (config.filter_conditions || []).filter((_, i) => i !== index);
                        setConfig({ ...config, filter_conditions: newConditions });
                      }}
                      className="p-2 text-red-600 hover:bg-red-50 rounded-md"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  )}
                </div>
              );
            })}
            
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => {
                const newConditions = [...(config.filter_conditions || []), { field: '', operator: 'equals', value: '' }];
                setConfig({ ...config, filter_conditions: newConditions });
              }}
              className="w-full border-dashed border-2"
            >
              + Add Condition
            </Button>
          </div>
        </div>
      )}

      {/* Output Variable */}
      {(config.action_type === 'create' || config.action_type === 'get') && (
        <div>
          <Label>Store Output In Variable</Label>
          <ResourcePickerField
            value={config.output_variable || ''}
            onChange={(value) => handleConfigChange('output_variable', value)}
            flowVariables={flowVariables}
            onCreateVariable={onCreateVariable}
            placeholder="Select or create variable"
          />
          <p className="text-xs text-slate-500 mt-1">
            {config.action_type === 'create' 
              ? 'Variable to store the created record ID'
              : 'Variable to store the retrieved record(s)'}
          </p>
        </div>
      )}
    </div>
  );
};

export default MCPConfigPanel;
