/**
 * Webhook Config Panel
 * Extracted from NodeConfigPanel.js - handles external API calls
 */
import React from 'react';
import { Label } from '../../../../components/ui/label';
import { Input } from '../../../../components/ui/input';
import { Textarea } from '../../../../components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../../../components/ui/select';
import { Button } from '../../../../components/ui/button';
import { Trash2 } from 'lucide-react';
import ResourcePickerField from '../ResourcePickerField';

// Utility: Generate API name from label
const generateApiName = (label) => {
  if (!label) return '';
  return label.toLowerCase().trim().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
};

const WebhookConfigPanel = ({
  config,
  setConfig,
  handleConfigChange,
  previousNodes,
  availableFields,
  fetchFieldsForObject,
  flowVariables
}) => {
  return (
    <div className="space-y-4">
      {/* Header Info */}
      <div className="bg-indigo-50 border border-indigo-200 rounded-lg p-3">
        <p className="text-sm text-indigo-800 font-medium">🔗 Webhook Element</p>
        <p className="text-xs text-indigo-600 mt-1">
          Make external API calls to integrate with external systems
        </p>
      </div>

      {/* Label and API Name in a row */}
      <div className="grid grid-cols-2 gap-3">
        <div>
          <Label>Label</Label>
          <Input
            className="w-full"
            value={config.label || ''}
            onChange={(e) => {
              const newLabel = e.target.value;
              const currentApiName = config.api_name || '';
              const oldAutoGeneratedApiName = generateApiName(config.label || '');
              const shouldAutoGenerate = !currentApiName || currentApiName === oldAutoGeneratedApiName;
              
              setConfig({ 
                ...config, 
                label: newLabel,
                api_name: shouldAutoGenerate ? generateApiName(newLabel) : currentApiName
              });
            }}
            placeholder="e.g., Call External API"
          />
        </div>
        <div>
          <Label>API Name</Label>
          <Input
            className="w-full font-mono bg-slate-50"
            value={config.api_name || ''}
            onChange={(e) => setConfig({ ...config, api_name: e.target.value })}
            placeholder="e.g., call_external_api"
          />
        </div>
      </div>

      {/* Description */}
      <div>
        <Label>Description</Label>
        <Textarea
          className="w-full"
          value={config.description || ''}
          onChange={(e) => handleConfigChange('description', e.target.value)}
          placeholder="Describe what this webhook does..."
          rows={3}
        />
      </div>

      {/* URL */}
      <div>
        <Label>URL</Label>
        <Input
          className="w-full font-mono"
          value={config.url || ''}
          onChange={(e) => handleConfigChange('url', e.target.value)}
          placeholder="https://api.example.com/endpoint"
        />
        <p className="text-xs text-slate-500 mt-1">The external API endpoint to call</p>
      </div>

      {/* HTTP Method */}
      <div>
        <Label>HTTP Method</Label>
        <Select
          value={config.http_method || 'POST'}
          onValueChange={(value) => handleConfigChange('http_method', value)}
        >
          <SelectTrigger className="w-full">
            <SelectValue placeholder="Select method" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="GET">GET</SelectItem>
            <SelectItem value="POST">POST</SelectItem>
            <SelectItem value="PUT">PUT</SelectItem>
            <SelectItem value="PATCH">PATCH</SelectItem>
            <SelectItem value="DELETE">DELETE</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Data Format */}
      <div>
        <Label>Data Format</Label>
        <Select
          value={config.data_format || 'json'}
          onValueChange={(value) => handleConfigChange('data_format', value)}
        >
          <SelectTrigger className="w-full">
            <SelectValue placeholder="Select format" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="json">JSON</SelectItem>
            <SelectItem value="xml">XML</SelectItem>
            <SelectItem value="form">Form Data</SelectItem>
          </SelectContent>
        </Select>
        <p className="text-xs text-slate-500 mt-1">Format of the request body</p>
      </div>

      {/* Headers */}
      <div className="space-y-3">
        <Label className="text-sm font-medium">Headers (Optional)</Label>
        
        {/* Column Headers */}
        <div className="grid grid-cols-2 gap-2 px-3">
          <div className="text-xs font-medium text-slate-600">Key</div>
          <div className="text-xs font-medium text-slate-600">Value</div>
        </div>
        
        {(config.headers || [{ key: '', value: '' }]).map((header, index) => (
          <div key={index} className="flex items-start gap-2 p-3 bg-slate-50 rounded-md border border-slate-200">
            <div className="flex-1 grid grid-cols-2 gap-2">
              <div>
                <Input
                  value={header.key || ''}
                  onChange={(e) => {
                    const newHeaders = [...(config.headers || [])];
                    newHeaders[index] = { ...newHeaders[index], key: e.target.value };
                    setConfig({ ...config, headers: newHeaders });
                  }}
                  placeholder="Authorization"
                />
              </div>
              <div>
                <Input
                  value={header.value || ''}
                  onChange={(e) => {
                    const newHeaders = [...(config.headers || [])];
                    newHeaders[index] = { ...newHeaders[index], value: e.target.value };
                    setConfig({ ...config, headers: newHeaders });
                  }}
                  placeholder="Bearer token123"
                />
              </div>
            </div>

            {/* Delete Button */}
            {(config.headers || []).length > 1 && (
              <button
                type="button"
                onClick={() => {
                  const newHeaders = (config.headers || []).filter((_, i) => i !== index);
                  setConfig({ ...config, headers: newHeaders });
                }}
                className="mt-0.5 p-2 text-red-600 hover:bg-red-50 rounded-md transition-colors"
                title="Delete header"
              >
                <Trash2 className="h-4 w-4" />
              </button>
            )}
          </div>
        ))}

        {/* Add Header Button */}
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => {
            const newHeaders = [...(config.headers || []), { key: '', value: '' }];
            setConfig({ ...config, headers: newHeaders });
          }}
          className="w-full border-dashed border-2 hover:border-indigo-400 hover:bg-indigo-50"
        >
          <span className="text-indigo-600 font-medium">+ Add Header</span>
        </Button>
      </div>

      {/* Payload Key-Value Pairs */}
      <div className="space-y-3">
        <Label className="text-sm font-medium">Payload (Request Body)</Label>
        
        {/* Column Headers */}
        <div className="grid grid-cols-2 gap-2 px-3">
          <div className="text-xs font-medium text-slate-600">Key</div>
          <div className="text-xs font-medium text-slate-600">Value</div>
        </div>
        
        {(config.payload || [{ key: '', value: '' }]).map((item, index) => (
          <div key={index} className="flex items-start gap-2 p-3 bg-slate-50 rounded-md border border-slate-200">
            <div className="flex-1 grid grid-cols-2 gap-2">
              <div>
                <Input
                  value={item.key || ''}
                  onChange={(e) => {
                    const newPayload = [...(config.payload || [])];
                    newPayload[index] = { ...newPayload[index], key: e.target.value };
                    setConfig({ ...config, payload: newPayload });
                  }}
                  placeholder="name"
                />
              </div>
              <div>
                <ResourcePickerField
                  value={item.value || ''}
                  onChange={(value) => {
                    const newPayload = [...(config.payload || [])];
                    newPayload[index] = { ...newPayload[index], value: value };
                    setConfig({ ...config, payload: newPayload });
                  }}
                  nodes={previousNodes}
                  availableFields={availableFields}
                  fetchFieldsForObject={fetchFieldsForObject}
                  flowVariables={flowVariables}
                  placeholder="Select value or type..."
                />
              </div>
            </div>

            {/* Delete Button */}
            {(config.payload || []).length > 1 && (
              <button
                type="button"
                onClick={() => {
                  const newPayload = (config.payload || []).filter((_, i) => i !== index);
                  setConfig({ ...config, payload: newPayload });
                }}
                className="mt-0.5 p-2 text-red-600 hover:bg-red-50 rounded-md transition-colors"
                title="Delete payload item"
              >
                <Trash2 className="h-4 w-4" />
              </button>
            )}
          </div>
        ))}

        {/* Add Payload Item Button */}
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => {
            const newPayload = [...(config.payload || []), { key: '', value: '' }];
            setConfig({ ...config, payload: newPayload });
          }}
          className="w-full border-dashed border-2 hover:border-indigo-400 hover:bg-indigo-50"
        >
          <span className="text-indigo-600 font-medium">+ Add Payload Item</span>
        </Button>
      </div>
    </div>
  );
};

export default WebhookConfigPanel;
